#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform sampler2D u_InputFrame;
layout(binding = 1, rgba16f) uniform writeonly image2D u_OutputLowRes;

layout(push_constant) uniform PushConstants {
    int in_width;
    int in_height;
    int out_width;
    int out_height;
} pc;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= pc.out_width || coord.y >= pc.out_height) {
        return;
    }

    vec2 uv = (vec2(coord) + 0.5) / vec2(pc.out_width, pc.out_height);
    vec4 color = texture(u_InputFrame, uv);

    imageStore(u_OutputLowRes, coord, color);
}
